[project]
name = "duplicity"
version = "3.1.0"
dynamic = ["dependencies"]
description = "Encrypted backup using rsync algorithm"
authors = [
    { name = "Kenneth Loafman", email = "kenneth@loafman.com" },
]
maintainers = [
    { name = "Edgar Soldin" },
    { name = "Thomas Laubrock" },
]
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
# not all LP builders will take license=
#license = "GPL-2.0-or-later"
classifiers = [
    "Development Status :: 6 - Mature",
    "Environment :: Console",
    "Operating System :: MacOS",
    "Operating System :: POSIX",
    "Programming Language :: C",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: System :: Archiving :: Backup",
]


[build-system]
requires = [
    "build>=1.1",
    "pip>=24.0",
    "pipx>=1.5",
    "packaging>=20.0",
    "setuptools>=78.1.0",
    "wheel>=0.42.0",
]
build-backend = "setuptools.build_meta"


[project.scripts]
duplicity = "duplicity.__main__:dup_run"


[project.urls]
Homepage = "http://duplicity.us"
Download = "https://gitlab.com/duplicity/duplicity/-/releases"
Issues = "https://gitlab.com/duplicity/duplicity/-/issues"
Contact = "https://lists.nongnu.org/mailman/listinfo/duplicity-talk"
Documentation = "http://duplicity.us"
Repository = "https://gitlab.com/duplicity/duplicity"
Changelog = "https://gitlab.com/duplicity/duplicity/-/blob/main/CHANGELOG.md"


[tool.setuptools]
platforms = [
    "any"
]


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}


[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "duplicity",
    "duplicity.backends",
    "duplicity.backends.pyrax_identity",
]
exclude = [
    ".*",
    "Makefile",
    "crowdin.yml",
    "debian*",
    "docs*",
    "readthedocs.yaml",
    "snap*",
    "testing*",
    "tools*",
    "venv*",
]


[tool.black]
line-length = 120
target-version = [
    "py310",
    "py311",
    "py312",
    "py313",
    "py314",
]


[tool.flynt]
line-length = 120
dry-run = true
aggressive = true
transform-concats = true
transform-joins = true
# TODO: Remove duplicity.argparse311 when py310 goes EOL
exclude = ["argparse311"]


[tool.pytest.ini_options]
addopts = [
    "--capture=fd",
    "--failed-first",
    "--showlocals",
    "--verbose",
    "-p no:hypothesis",
    "-p no:randomly",
    "-p no:xdist",
]
testpaths = [
    "testing/test_code.py",
    "testing/unit",
    "testing/functional",
]


[tool.cibuildwheel]
before-build = [
    # Clean up stale build folders and old egg-info before compiling each wheel
    # to build_ext with proper python version.  Build any extensions needed.
    # make sure we build_ext with the current python
    "rm -rf build/ *.egg-info",
    "rm -rf .setuptools-cmake-build _skbuild",
    # install all the python requirements but not lxml
    "python -m pip install -q --upgrade pip",
    "grep -v lxml requirements.txt > requirements.whl",
    "python -m pip install -q -r requirements.whl",
    "python ./setup.py build_ext",
]

[tool.cibuildwheel.config-settings]
build-option = "--use-pep517"

[tool.cibuildwheel.linux]
before-all = [
    # WARNING: wheel builds are RedHat-based, not Debian.
    "yum update -y",
    "yum install -y gcc gcc-c++ make git intltool librsync-devel",
    "yum install -y libffi-devel openssl-devel openssl tzdata",
    "yum install -y libxml2-devel libxslt-devel python3-lxml",
]
archs = [
    "aarch64",
#    "armv7l",  # is 32-bit
#    "ppc64le",  # lxml build fails
#    "riscv64",  # no librsync-devel
#    "s390x",  # lxml build fails
    "x86_64",
]
build = [
    "cp{310,311,312,313,314}-manylinux_aarch64",
#    "cp{310,311,312,313,314}-manylinux_armv7l",  # is 32-bit
#    "cp{310,311,312,313,314}-manylinux_ppc64le",  # lxml build fails
#    "cp{310,311,312,313,314}-manylinux_riscv64",  # no librsync-devel
#    "cp{310,311,312,313,314}-manylinux_s390x",  # lxml build fails
    "cp{310,311,312,313,314}-manylinux_x86_64",
]

[tool.cibuildwheel.macos]
environment = "LIBRSYNC_DIR=$HOMEBREW_PREFIX MACOSX_DEPLOYMENT_TARGET=26.0"
before-all = [
    # install packages using homebrew
    "echo $LIBRSYNC_DIR",
    "brew install cmake intltool librsync",
]
archs = [
    "arm64",
    "x86_64",
]
build = [
    "cp{310,311,312,313,314}-macosx_arm64",
    "cp{310,311,312,313,314}-macosx_x86_64",
]


[tool.pylint]
jobs = 0
errors-only = "yes"
ignore = "_librsync.so"
msg-template = '{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}'
disable = [
    "C",
    "R",
    "invalid-name",
    "line-too-long",
    "missing-function-docstring",
    "missing-module-docstring",
    "no-member",
    "no-name-in-module",
    "not-callable",
    "possibly-used-before-assignment",
    "raise-missing-from",
    "unexpected-keyword-arg",
    "undefined-variable",
    "wrong-import-order",
    "wrong-import-position",
]
enable = [
    "unused-argument",
    "access-member-before-definition",
    "unused-wildcard-import",
    "redefined-builtin",
    "bad-indentation",
    "mixed-indentation",
    "unreachable",
]
